EXTENSION_MAP = {
    ".ckpt": "checkpoints",
    ".safetensors": "checkpoints",
    ".sft": "checkpoints",
    ".vae": "vaes",
    ".pt": "loras",
    ".bin": "clip_models",
    ".pth": "controlnets",
    ".upscale": "upscalers",
    ".embedding": "embeddings",
    ".yaml": "styles",
    ".json": "configurations",
    ".inpainting": "inpainting",
    ".depth": "depth_models",
    ".pose": "pose_models",
    ".sam": "sam_models",
    ".h5": "custom_models",
    ".onnx": "onnx_models",
    ".mlmodel": "coreml_models",
    ".weights": "miscellaneous",
    ".txt": "metadata",
    ".log": "logs",
}
